name: Node.js CI/CD Pipeline

on: #триггеры для запуска workflow
  push: #после каждого пуша в ветке main
    branches: [main]
  pull_request: #при создании или обновлении pull request, связанной с веткой main
    branches: [main]

jobs:
  build_and_test: #первая джоба - сборка и тестирование    
    name: Build and test on other OS
    runs-on: ${{ matrix.os }} #выполнение в ОС ubuntu, windows, macos согласно массиву matrix.os
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout Code #шаг по клонированию кода из репозитория 
      uses: actions/checkout@v3
    - name: Set up Node.js #шаг по установке Node.js 16 версии
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies #установка зависимостей, указанных в файле package.json
      run: npm install
    - name: Run tests #запуска теста (выполнение тестового файла app.test.js)
      run: npm test

  deploy: #вторая джоба - деплой на dockerhub
    runs-on: ubuntu-latest #запуск на ubuntu
    needs: build_and_test #для запуска требуется выполнение прошлой джобы
    steps:
      - uses: actions/checkout@v3 #шаг по клонированию кода из репозитория 
      - name: Login to Docker Hub #шаг по авторизайции в Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} #Логин - указан в secrets к проекту
          password: ${{ secrets.DOCKER_PASSWORD }} #Пароль - указан в secrets к проекту
      - name: Build and Push image to Docker Hub #сборка и пуш образа в Dockerhub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: lenargilmanov/mynodeapp #Как будет называться контейнер
